apiVersion: apps/v1
kind: Deployment
metadata:
    name: flight-depl
spec:
    replicas: 1
    selector:
        matchLabels:
            app: flight
    template:
        metadata:
            labels:
                app: flight
        spec:
            containers:
                - name: flight
                  image: jogeshgupta963/flight
                  imagePullPolicy: Never
                  env:
                      - name: MONGO_URI
                        value: "mongodb://flight-mongo-srv:27017/flight"
                      #   - name: JWT_SECRET
                      #     valueFrom:
                      #         secretKeyRef:
                      #             name: jwt-secret
                      #             key: JWT_SECRET
---
apiVersion: v1
kind: Service
metadata:
    name: flight-srv
spec:
    selector:
        app: flight
    type: ClusterIP
    ports:
        - name: flight
          protocol: TCP
          port: 3000
          targetPort: 3000
