apiVersion: apps/v1
kind: Deployment
metadata:
    name: profile-mongo-depl
spec:
    replicas: 1
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxSurge: 1
            maxUnavailable: 1
    minReadySeconds: 5
    selector:
        matchLabels:
            app: profile-mongo
    template:
        metadata:
            labels:
                app: profile-mongo
        spec:
            containers:
                - name: mongo
                  image: mongo
                  ports:
                      - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
    name: profile-mongo-srv
spec:
    type: ClusterIP
    selector:
        app: profile-mongo
    ports:
        - name: profile-mongo
          protocol: TCP
          port: 27017
          targetPort: 27017
