apiVersion: apps/v1
kind: Deployment
metadata:
    name: profile-postgres-depl
spec:
    replicas: 1
    # strategy:
    #     type: RollingUpdate
    #     rollingUpdate:
    #         maxSurge: 1
    #         maxUnavailable: 1
    # minReadySeconds: 5
    selector:
        matchLabels:
            app: profile-postgres
    template:
        metadata:
            labels:
                app: profile-postgres
        spec:
            containers:
                - name: postgres
                  image: postgres:10.1
                  ports:
                      - containerPort: 5432
                  env:
                      - name: POSTGRES_DB
                        value: db0
                      - name: POSTGRES_USER
                        value: USER
                      - name: POSTGRES_PASSWORD
                        value: USER

---
apiVersion: v1
kind: Service
metadata:
    name: profile-postgres-srv
spec:
    type: ClusterIP
    selector:
        app: profile-postgres
    ports:
        - name: profile-postgres
          protocol: TCP
          port: 5432
          targetPort: 5432
