apiVersion: apps/v1
kind: Deployment
metadata:
    name: profile-depl
spec:
    replicas: 1
    selector:
        matchLabels:
            app: profile
    template:
        metadata:
            labels:
                app: profile
        spec:
            containers:
                - name: profile
                  image: jogeshgupta963/profile
                  imagePullPolicy: Never
                  env:
                      - name: MONGO_URI
                        value: "mongodb://profile-postgres-srv:27017/profile"
                      #   - name: JWT_SECRET
                      #     valueFrom:
                      #         secretKeyRef:
                      #             name: jwt-secret
                      #             key: JWT_SECRET
---
apiVersion: v1
kind: Service
metadata:
    name: profile-srv
spec:
    selector:
        app: profile
    type: ClusterIP
    ports:
        - name: profile
          protocol: TCP
          port: 3000
          targetPort: 3000
